ENCODER_MODE="auto"

LOW_BITRATE="4000k"
LOW_BUFSIZE="8000k"
LOW_CPU="1 Core"

MEDIUM_BITRATE="8000k"
MEDIUM_BUFSIZE="16000k"
MEDIUM_CPU="2 Core"

HIGH_BITRATE="12000k"
HIGH_BUFSIZE="24000k"
HIGH_CPU="4 Core"

ULTRA_BITRATE="20000k"
ULTRA_BUFSIZE="40000k"
ULTRA_CPU="8+ Core"
